language: java
install:
  - sudo chmod 777 gradlew
jdk:
  - openjdk8
script:
  - sudo chmod 777 gradlew
  - sudo ./gradlew setupDecompWorkspace
  - sudo ./gradlew build
  - sudo chmod 777 src/main/resources/mcmod.info
sudo: true
addons:
  apt:
    packages:
      - oracle-java8-installer